apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xmasiarikova-ambulance-ufe-content
spec:
  microFrontend: xmasiarikova-ambulance-ufe
  element: xmasiarikova-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: bobulova
    - name: base-path
      value: /xmasiarikova-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xmasiarikova-ambulance-wl(/.*)?$"