apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: mirusm/ambulance-ufe
  newName: mirusm/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260317.2023 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: mirusm/ambulance-wl-webapi
  newName: mirusm/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
