apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: xmasiarikova-ambulance-wl
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/xmasiarikova-ambulance-ufe


components:
- ../../../components/version-release