apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: xmasiarikova-ambulance-wl
    wac-fiit.github.io/project: xmasiarikova-ambulance-wl
  includeTemplates: true

resources:
- ../../../apps/xmasiarikova-ambulance-ufe
- ../../../apps/xmasiarikova-ambulance-webapi


components:
- ../../../components/version-release